### ISSUE TITLE
Much of the Right-Pane Startup Dialogue is Omitted

### ISSUE THREAD

**Issue by ThisNekoGuy** [patriceac/Stable-Diffusion-UI-plugins#1]
Using this plugin cuts out much of the initial startup dialogue in the right pane.
Would like to have this consistency back

<details><summary>Without this plugin:</summary>

![Screenshot_20221205_204227](https://user-images.githubusercontent.com/28468662/205796104-fa9c66c0-c722-4d55-bac1-eeb07cb14d22.png)
</details>
<details><summary>With this plugin:</summary>

![Screenshot_20221205_204148](https://user-images.githubusercontent.com/28468662/205795902-c7bca86d-568f-4205-af85-227ec2d21554.png)
</details>

**Comment by patriceac** [comment]
Are you using Main or Beta? What other plugins do you have active?

**Comment by ThisNekoGuy** [comment]
Main; and these are my plugins:
```
Don-t-leave.plugin.js  Ski-SDUI-MoreRes.plugin.js  spell-tokenizer.plugin.js
```

**Comment by patriceac** [comment]
Still doesn't repro for me. What browser/OS do you use?

**Comment by ThisNekoGuy** [comment]
I use [LibreWolf](https://librewolf.net) on [Arch Linux](https://archlinux.org)

For this reason:
https://privacytests.org/

**Comment by patriceac** [comment]
Thanks. A new version of the plugin has been merged into Beta and should work as expected. I would recommend removing this plugin from your plugins folder to avoid any conflict.
